---
#- template:
#    src: config.j2
#    dest: /tmp/whatever

- debug:
    msg: "Index is {{ groups['scaleout'].index(inventory_hostname)  }}  {{ groups['scaleout'] | length }} "
#  loop: "{{ query('inventory_hostnames', 'scaleout') }}"
#  loop_control:
#    index_var: my_idx

#    priority: "{{ groups['scaleout'].index(inventory_hostname) + 1 }}"
#    id: "{{ groups['scaleout'].index(inventory_hostname) + 1 }}"
- name: Create a10_scaleout_cluster_local_device instance
  a10_scaleout_cluster_local_device:
    a10_host: "{{ inventory_hostname }}"
    a10_username: "{{ a10_username }}"
    a10_password: "{{ a10_password }}"
    priority: "{{ a10scaleout_id }}"
    id: "{{ a10scaleout_id }}"
    cluster_id: 1
