---
#  loop: "{{ query('inventory_hostnames', 'scaleout') }}"
#  loop_control:
#    index_var: my_idx
#      device_id: "{{ groups['scaleout'].index(inventory_hostname) + 1 }}"
#      ip: "{{ inventory_hostname }}"
- name: Create a10_scaleout_cluster_cluster_devices_device_id example playbook
  loop: "{{ query('inventory_hostnames', 'scaleout') }}"
  loop_control:
    index_var: my_idx
  a10_scaleout_cluster_cluster_devices_device_id:
      a10_host: "{{ item }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      device_id: "{{ a10scaleout_id }}"
      ip: "{{ a10_host }}"
      cluster_id: 1
