---
- name: Create a10_scaleout_cluster_device_groups example playbook
  a10_scaleout_cluster_device_groups:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      cluster_id: 1
      device_group_list: 
      - device_group: 5
      - device_id_list: [
       {
        "device-id-start": 4,
        "device-id-end": 6
       }
       ]

